### ISSUE TITLE
Don't fail when class is only found in one of scaladsl/javadsl but fqn was given

### ISSUE THREAD

**Issue by jrudolph** [lightbend/sbt-paradox-apidoc#48]
I.e. it is intended to link to the japidoc for a scaladsl class.

**Comment by ennru** [comment]
See https://github.com/lightbend/sbt-paradox-apidoc/pull/84#pullrequestreview-320084067

**Comment by raboof** [comment]
I think the fact that this now throws is rather a feature: otherwise we would accidentally link to scaladsl classes in the java version of the docs, or javadsl classes in the scala version of the docs.

I think if you really want that you should just use the javadoc/scaladoc directives instead of unidoc (although I can see how it's painful to go back now that unidoc is getting so nice ;) )
